# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build API
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Ommi.API/Dockerfile'
        tags: |
          $(tag)
    - task: NodeTool@0
      inputs:
      versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
            npm install
            npm run build
      displayName: 'npm install and build