# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Ommi.API/*
    - api.yml
    exclude:
    - ommi.client/*
    - client.yml
    - Architecture/*
    

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'ommidockerrepo'
  azureServiceConnectionName: 'ommidockerregistry-acr'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build API project image and push to ACR
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(azureServiceConnectionName)

    - task: Docker@2
      displayName: Build and Push
      inputs:
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/Ommi.API/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: $(azureServiceConnectionName)